rules:
  - match: "*vae*"
    path: "vae"
  - match: "*lora*"
    path: "loras"
  - match: "*controlnet*"
    path: "controlnet"
  - match: "*clip*"
    path: "clip"
  - match: "t5xxl*"
    path: "clip"
  - match: "*unet*"
    path: "unet"
  - match: "flux1-*.safetensors"
    path: "unet"
  - match: "*.safetensors"
    path: "checkpoints"
  - match: "*.ckpt"
    path: "checkpoints"
